### ISSUE TITLE
OpenJDK-7-jdk no longer available on Debian 9

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/VagrantBuild#4]
In the Ansible provisioning role (android_tamer_essential), you are trying to [install openjdk-7-jdk](https://github.com/AndroidTamer/VagrantBuild/blob/master/provisioning/roles/android_tamer_essential/tasks/main.yml#L38). But for Debian 9, its no longer available.

Check out [StackOverflow](https://stackoverflow.com/questions/46615152/debian-9-openjdk-7-jre-and-openjdk-7-jre-headless)

**Comment by anantshri** [comment]
we are moving to openjdk 11 and 17 for tamer5 with debian 11 lets, will update with more info as build's progress.
